### ISSUE TITLE
Update Wiki

### ISSUE THREAD

**Issue by appandweb** [voghDev/dagger2-clean-mvp-example#1]
Add naming conventions for:

* layouts (lyt_)
* scrollViews (scrv_ or _scrollView)
* ImageButtons (ibtn_)
* ProgressButtonViews (btn_)
* ProgressBars (pbr_ or R.id.progressBar)
* RecyclerViews (rv_ or R.id.recyclerView)

**Comment by voghDev** [comment]
Done, thanks
